### ISSUE TITLE
Hello Author! I read your paper and found your research interesting and helpful, may I ask when do you plan to make the code publicly available

### ISSUE THREAD

**Issue by wanwandm** [s-sahoo/MuLAN#1]
Hello Author! I read your paper and found your research interesting and helpful, may I ask when do you plan to make the code publicly available

**Comment by s-sahoo** [comment]
We're hoping to release the code by the end of this month. Sorry for the delay.

**Comment by yasin-esfandiari** [comment]
Hello Authors. Thanks for your great work. Would it be possible for you to release the code, or provide an estimate regarding the release date?
